---
title: "PayPal Report"
author: "David Barron"
date: "`r format(Sys.Date(), '%d %B %Y' )`"
output:
  pdf_document: default
  html_document:
    theme:
      bg: '#FFF8DC'
      fg: '#000080'
      primary: '#00FF00'
      base_font: Georgia
      heading_font: Arial
---

```{r setup, include=TRUE, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error=TRUE, cache=FALSE)
library(knitr)
library(kableExtra)
library(here)

options(knitr.kable.NA = '')

# Format money output
inline_hook <- function(x){
  format(x, nsmall = 2, scientific = FALSE, big.mark = ",")
}

knit_hooks$set(inline = inline_hook)

```

```{r intro}
library(tidyverse)
library(readxl)

```

```{r readdata}
yr <- "2025"

fn <- paste0("PayPal", yr, ".xlsx" ) 

pp_dta <- read_xlsx(fn,
   sheet = "PayPal")

pp_dta <- pp_dta %>%
  select(Date, Name, Gross, Fee, Net, Type, Item = `Item Title`, Status, Balance)

nrows <- dim(pp_dta)[1]
```

```{r pivottable}
sum_dta <- function(dta){
  dta %>%
    filter(Status == "Completed",
           Type != "General Withdrawal",
           Type != "General Currency Conversion",
           Type != "Bank deposit to PayPal account") %>%
    mutate(Date = lubridate::ymd(Date),
           Month = lubridate::month(Date)) %>%
    group_by(Item) %>%
    summarise(
        Net = sum(Net)
    )  
}

tot_income <- function(dta){
  dta %>%
    filter(Status == "Completed",
           Type == "General Withdrawal") %>%
          mutate(Date = lubridate::ymd(Date),
                 Month = lubridate::month(Date)) %>%
        group_by(Month) %>%
        summarise(
          Gross = -1 * sum(Gross)
        )  
}

sum_pp_dta <- sum_dta(pp_dta)

pp_inc <- tot_income(pp_dta)

```

```{r summary}

sum_pp_dta %>% kbl(caption = "PayPal transactions") %>% 
  kable_classic(full_width = FALSE, html_font = "Georgia") %>%
  kable_styling(latex_options = c("hold_position", "scale_down"))

paypal_balance <- as.numeric(pp_dta[nrows, "Balance"])
```


PayPal balance: **£`r paypal_balance`**